### ISSUE TITLE
incorrect number of lines

### ISSUE THREAD

**Issue by jake-stewart** [NikitaRevenco/instant-lsp.nvim#2]
### Environment

**Neovim**: v0.10.2 Release
**Lua**: LuaJIT 2.1.1727870382
**OS**: macOS 14.6.1 23G93 arm64
**Host**: Mac14,5
**Kernel**: 23.6.0
**Shell**: zsh 5.9
**Terminal**: tmux
**CPU**: Apple M2 Max

### Problem

The README states that the plugin can be installed with a single line of code, but the example provided demonstrates that the installation process requires 13 lines of code. This creates a mismatch between the documented claim and the actual implementation, which could lead to confusion for users following the instructions.

### Description

In the documentation or example provided by the plugin author, the installation process is described as simple, requiring only a single line of code to get the plugin up and running. However, when users attempt to follow the example or run the installation as described, they find that the process involves several more steps, with a total of 13 lines of code in the actual installation. This discrepancy could be misleading for beginners or anyone trying to quickly implement the plugin, especially when the expectation is set that it should be much simpler.

The 13 lines of code in the example include necessary configurations, setup, or additional commands that should either be clarified in the documentation or perhaps streamlined if possible. Without further clarification, users might expect an overly simplified process and be confused by the extra steps involved.

This problem could also lead to frustration if users believe they are missing something, or worse, they might assume that the documentation is incorrect or incomplete.

### Example

I ran the command `nl` on my `init.lua` configuration file:

```
16:41 jakey $ nl init.lua
     1  local instant_lsp_path = vim.fn.stdpath("data") .. "/instant-lsp.nvim"

     2  -- Clone the plugin onto your system
     3  if not vim.loop.fs_stat(instant_lsp_path) then
     4          vim.fn.system({
     5                  "git",
     6                  "clone",
     7                  "--filter=blob:none",
     8                  "https://github.com/nikitarevenco/instant-lsp.nvim",
     9                  instant_lsp_path,
    10          })
    11  end

    12  -- Let neovim recognize the plugin's path so we can require it
    13  vim.opt.rtp:prepend(instant_lsp_path)
```

As you can see with the line numbers next to the lines, there are 13 lines instead of the expected 1 line.

### Expected Result

The installation process should be clearly communicated, and if the plugin truly requires only a single line of code, the example should reflect this. If additional steps are necessary, these should be properly explained, and the documentation should avoid giving the impression that the installation is significantly simpler than it actually is.

Ideally, the example could be updated to either show the exact steps for installation or indicate why more than a single line of code is required to complete the setup. This would ensure that users are prepared for the correct installation process without feeling misled or confused.

**Comment by NikitaRevenco** [comment]
Thank you for the extremely detailed issue! 

Please note that I don't work on this repo anymore since I don't use neovim anymore. this is mentioned at the top of the README
